import { Type } from '@google/genai';

const queryActions = [
    'server_overview',
    'list_members',
    'online_members',
    'voice_members',
    'member_profile',
    'member_permissions',
    'channel_overview',
    'channel_permissions',
    'channel_overwrites',
    'list_channels',
    'list_roles',
    'role_overview',
    'role_members',
    'recent_messages',
    'pinned_messages',
    'message_overview',
    'reaction_users',
    'list_emojis',
    'list_stickers',
    'list_soundboard_sounds',
    'forum_tags',
    'list_bans',
    'list_invites',
    'list_scheduled_events',
    'scheduled_event_subscribers',
    'list_active_threads',
    'list_archived_threads',
    'thread_members',
    'list_webhooks',
    'list_automod_rules',
    'list_integrations',
    'list_commands',
    'audit_log_recent',
    'server_vanity',
    'welcome_screen',
    'bot_permissions',
    'bot_profile'
];

const actionActions = [
    'send_message',
    'reply_replied_message',
    'edit_replied_bot_message',
    'delete_replied_message',
    'delete_recent_from',
    'bulk_delete_recent',
    'react_replied_message',
    'remove_bot_reaction_replied',
    'remove_user_reaction_replied',
    'clear_reactions_replied',
    'pin_replied_message',
    'unpin_replied_message',
    'suppress_embeds_replied',
    'unsuppress_embeds_replied',
    'crosspost_replied_message',
    'forward_replied_message',
    'send_poll',
    'end_replied_poll',
    'send_typing',
    'set_nickname',
    'clear_nickname',
    'timeout',
    'clear_timeout',
    'disconnect_voice',
    'move_voice',
    'voice_mute',
    'voice_unmute',
    'voice_deafen',
    'voice_undeafen',
    'stage_invite_to_speak',
    'stage_move_to_audience',
    'stage_request_to_speak',
    'stage_cancel_request',
    'add_role',
    'remove_role',
    'kick',
    'ban',
    'unban',
    'dm_member',
    'create_text_channel',
    'create_voice_channel',
    'create_category',
    'create_announcement_channel',
    'create_stage_channel',
    'create_forum_channel',
    'rename_channel',
    'set_channel_topic',
    'set_channel_slowmode',
    'set_channel_nsfw',
    'set_channel_parent',
    'set_channel_position',
    'set_voice_bitrate',
    'set_voice_user_limit',
    'lock_channel',
    'unlock_channel',
    'hide_channel',
    'show_channel',
    'sync_channel_permissions',
    'edit_channel_permissions',
    'delete_channel_permissions',
    'clone_channel',
    'delete_channel',
    'create_invite',
    'delete_invite',
    'follow_announcement',
    'create_webhook',
    'edit_webhook',
    'delete_webhook',
    'send_webhook',
    'create_thread',
    'create_thread_from_replied',
    'create_forum_post',
    'rename_thread',
    'archive_thread',
    'unarchive_thread',
    'lock_thread',
    'unlock_thread',
    'set_thread_auto_archive',
    'set_thread_slowmode',
    'set_thread_invitable',
    'pin_forum_thread',
    'unpin_forum_thread',
    'add_thread_member',
    'remove_thread_member',
    'set_forum_tags',
    'set_forum_default_reaction',
    'set_forum_default_slowmode',
    'create_role',
    'rename_role',
    'set_role_color',
    'set_role_hoist',
    'set_role_mentionable',
    'set_role_position',
    'set_role_permissions',
    'set_role_icon',
    'set_role_unicode_emoji',
    'delete_role',
    'set_bot_username',
    'set_bot_avatar',
    'set_bot_banner',
    'set_bot_status',
    'set_bot_activity',
    'clear_bot_activity',
    'rename_server',
    'set_server_description',
    'set_server_icon',
    'set_server_banner',
    'set_server_splash',
    'set_afk_channel',
    'set_afk_timeout',
    'set_system_channel',
    'set_rules_channel',
    'set_public_updates_channel',
    'set_safety_alerts_channel',
    'create_emoji',
    'rename_emoji',
    'delete_emoji',
    'create_sticker',
    'edit_sticker',
    'delete_sticker',
    'create_soundboard_sound',
    'edit_soundboard_sound',
    'delete_soundboard_sound',
    'play_soundboard_sound',
    'create_external_event',
    'create_voice_event',
    'rename_scheduled_event',
    'set_event_description',
    'set_event_start_time',
    'set_event_end_time',
    'set_event_location',
    'start_scheduled_event',
    'complete_scheduled_event',
    'cancel_scheduled_event',
    'delete_scheduled_event',
    'create_stage_instance',
    'edit_stage_topic',
    'delete_stage_instance',
    'create_keyword_automod',
    'create_mention_spam_automod',
    'rename_automod_rule',
    'enable_automod_rule',
    'disable_automod_rule',
    'delete_automod_rule'
];

export const discordTools = [
    {
        name: 'discord_query',
        description: 'Đọc dữ liệu Discord trực tiếp bằng discord.js. Dùng trước agent_code cho mọi dữ liệu guild/member/channel/message/role/emoji/thread/invite/event/audit có action tương ứng. Các object trả về có thể được gán entity ref tạm như channel1, role1, ban1 để dùng tiếp trong cùng lượt.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                action: { type: Type.STRING, enum: queryActions },
                target: { type: Type.STRING, description: 'Entity ref như author, bot, u1, recent1, current_channel, replied_message, role1, channel1, event1...' },
                secondary_target: { type: Type.STRING, description: 'Entity ref phụ khi cần, ví dụ member để xem permission trong channel.' },
                limit: { type: Type.INTEGER, description: 'Giới hạn số kết quả. Mặc định nhỏ để phản hồi nhanh.' },
                emoji: { type: Type.STRING, description: 'Emoji cho reaction_users, ví dụ 👍 hoặc tên/id custom emoji.' }
            },
            required: ['action']
        }
    },
    {
        name: 'discord_action',
        description: 'Thực hiện thao tác Discord trực tiếp bằng discord.js, không sinh script. Mutations là owner-only ở executor. Dùng entity refs từ Discord Context hoặc refs vừa được discord_query trả trong cùng lượt; không tự đoán Snowflake ID/tên.',
        parameters: {
            type: Type.OBJECT,
            properties: {
                action: { type: Type.STRING, enum: actionActions },
                target: { type: Type.STRING, description: 'Entity chính: user/channel/message/role/emoji/sticker/event/thread/invite/sound/automod.' },
                secondary_target: { type: Type.STRING, description: 'Entity phụ, ví dụ role cho add_role, channel cho move_voice, member cho thread member.' },
                name: { type: Type.STRING },
                nickname: { type: Type.STRING },
                content: { type: Type.STRING },
                description: { type: Type.STRING },
                topic: { type: Type.STRING },
                reason: { type: Type.STRING },
                emoji: { type: Type.STRING },
                color: { type: Type.STRING, description: 'Màu role dạng #RRGGBB.' },
                count: { type: Type.INTEGER },
                duration_minutes: { type: Type.INTEGER },
                delete_message_seconds: { type: Type.INTEGER },
                slowmode_seconds: { type: Type.INTEGER },
                bitrate: { type: Type.INTEGER },
                user_limit: { type: Type.INTEGER },
                position: { type: Type.INTEGER },
                max_age_seconds: { type: Type.INTEGER },
                max_uses: { type: Type.INTEGER },
                temporary: { type: Type.BOOLEAN },
                unique: { type: Type.BOOLEAN },
                enabled: { type: Type.BOOLEAN },
                hoist: { type: Type.BOOLEAN },
                mentionable: { type: Type.BOOLEAN },
                nsfw: { type: Type.BOOLEAN },
                attachment_target: { type: Type.STRING, description: 'Attachment ref a1/ra1 để tạo emoji/sticker/soundboard.' },
                tags: { type: Type.STRING, description: 'Unicode emoji/tag bắt buộc cho sticker.' },
                volume: { type: Type.NUMBER, description: 'Soundboard volume từ 0 đến 1.' },
                start_time: { type: Type.STRING, description: 'ISO-8601 datetime cho scheduled event.' },
                end_time: { type: Type.STRING, description: 'ISO-8601 datetime cho external scheduled event.' },
                location: { type: Type.STRING, description: 'Địa điểm external scheduled event.' },
                poll_question: { type: Type.STRING },
                poll_answers: { type: Type.ARRAY, items: { type: Type.STRING } },
                poll_duration_hours: { type: Type.INTEGER },
                keywords: { type: Type.ARRAY, items: { type: Type.STRING } },
                permissions: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'Danh sách Discord permission names cho role, ví dụ ViewChannel/SendMessages.' },
                allow_permissions: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'Permission names cần Allow trong channel overwrite.' },
                deny_permissions: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'Permission names cần Deny trong channel overwrite.' },
                clear_permissions: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'Permission names cần trả về inherit/null trong channel overwrite.' },
                auto_archive_minutes: { type: Type.INTEGER, description: 'Thread auto archive: 60, 1440, 4320 hoặc 10080 phút.' },
                afk_timeout_seconds: { type: Type.INTEGER, description: 'AFK timeout server, đơn vị giây.' },
                status: { type: Type.STRING, description: 'Bot presence: online, idle, dnd, invisible.' },
                activity: { type: Type.STRING, description: 'Nội dung activity/presence của bot.' },
                activity_type: { type: Type.STRING, description: 'playing, listening, watching, competing.' },
                forum_tags: { type: Type.ARRAY, items: { type: Type.STRING }, description: 'Tên tag forum. Với set_forum_tags sẽ thay toàn bộ danh sách tag.' },
                custom_message: { type: Type.STRING },
                mention_total_limit: { type: Type.INTEGER }
            },
            required: ['action']
        }
    }
];
